repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      - id: check-ast
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: [--unsafe]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black
        args: # arguments to configure black
          - --line-length=120
        name: Run black formatter
        language_version: python3.10
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: # arguments to configure flake8
          # making isort line length compatible with black
          - "--max-line-length=120"
        name: Run flake8 linter
        additional_dependencies: ["flake8-bugbear==20.11.1", "pep8-naming==0.11.1"]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        additional_dependencies: [toml]
        name: Sort imports using isort
  - repo: https://github.com/hukkinj1/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        name: Format Markdown files
